package view;

import controller.AuditLogController;
import model.AuditLog;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

import java.awt.event.*;
import javax.swing.table.TableRowSorter;

import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.ArrayList;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.Document;

//class audit
public class auditlog extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    private AuditLogController logController = new AuditLogController();
    private JTextField jTextField1 = new JTextField();
    private DefaultTableModel dm;
    private TableRowSorter<DefaultTableModel> tr;
    private javax.swing.JTextField textField2 = new javax.swing.JTextField();

    public auditlog() {
        initComponents();
        setBackground(new java.awt.Color(0, 0, 0, 0));
        setupTable();
        loadLog();

        jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setHorizontalAlignment(SwingConstants.CENTER);
                return label;
            }
        });

        jTable1.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                label.setBackground(new Color(159, 2, 2));  // warna biru
                label.setForeground(new Color(237, 219, 195)); // teks cream
                label.setHorizontalAlignment(JLabel.CENTER); // opsional: teks di tengah
                label.setFont(label.getFont().deriveFont(Font.BOLD)); // font tebal
                label.setOpaque(true);                           // supaya background muncul
                return label;
            }
        });

        // Buat latar form transparan
        setBackground(new java.awt.Color(0, 0, 0, 0));

        // Hilangkan grid di dalam tabel
        jTable1.setShowGrid(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer) jTable1.getDefaultRenderer(Object.class)).setOpaque(false);

        // Buat scroll pane transparan 
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBorder(null);

        dm = (DefaultTableModel) jTable1.getModel();
        tr = new TableRowSorter<>(dm);
        jTable1.setRowSorter(tr);
    }

    private void setupTable() {
        // Buat model dengan kolom ID, Tanggal, Aksi
        tableModel = new DefaultTableModel(new Object[]{"ID", "Tanggal", "Aksi"}, 0);
        jTable1.setModel(tableModel);
    }

    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = (TableRowSorter<DefaultTableModel>) jTable1.getRowSorter();

        if (query == null || query.trim().isEmpty()) {
            tr.setRowFilter(null); // Hapus filter jika query kosong
        } else {
            // [TEMPATKAN KODE FILTER DI SINI]
            List<RowFilter<Object, Object>> filters = new ArrayList<>();
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                filters.add(RowFilter.regexFilter("(?i)" + query, i));
            }
            tr.setRowFilter(RowFilter.orFilter(filters));
        }
    }

    private void loadLog() {
        // Kosongkan isi tabel terlebih dahulu
        tableModel.setRowCount(0);

        List<AuditLog> logList = logController.getSemuaLog(); // Ambil data dari DB
        for (AuditLog log : logList) {
            tableModel.addRow(new Object[]{
                log.getId(),
                log.getTanggal(),
                log.getAksi()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uASPBO1 = new view.UASPBO();
        logging = new view.UASPBO();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        uASPBO5 = new view.UASPBO();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();

        uASPBO1.setBackground(new java.awt.Color(255, 235, 202));
        uASPBO1.setPreferredSize(new java.awt.Dimension(812, 485));
        uASPBO1.setRoundBottomLeft(100);
        uASPBO1.setRoundBottomRight(100);

        logging.setBackground(new java.awt.Color(255, 235, 202));
        logging.setOpaque(true);
        logging.setRoundBottomLeft(100);
        logging.setRoundBottomRight(100);
        logging.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel4.setText("Search...");
        logging.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 74, 60, 20));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("AUDIT LOGGING");
        logging.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 18, -1, -1));

        uASPBO5.setBackground(new java.awt.Color(255, 153, 153));
        uASPBO5.setRoundBottomLeft(50);
        uASPBO5.setRoundBottomRight(50);
        uASPBO5.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Aksi"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        uASPBO5.add(jScrollPane1, "card2");

        logging.add(uASPBO5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 750, 330));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        logging.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 200, 25));

        javax.swing.GroupLayout uASPBO1Layout = new javax.swing.GroupLayout(uASPBO1);
        uASPBO1.setLayout(uASPBO1Layout);
        uASPBO1Layout.setHorizontalGroup(
            uASPBO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logging, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        uASPBO1Layout.setVerticalGroup(
            uASPBO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uASPBO1Layout.createSequentialGroup()
                .addComponent(logging, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(uASPBO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(uASPBO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {
        if (jTextField2.getText() == null) {
            return;
        }
        String query = jTextField2.getText().toLowerCase();
        filter(query);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private view.UASPBO logging;
    private view.UASPBO uASPBO1;
    private view.UASPBO uASPBO5;
    // End of variables declaration//GEN-END:variables
}
