package view;

import controllerGUI.CicilanControllerGUI;
import controllerGUI.PembelianControllerGUI;
import controllerGUI.PenjualanControllerGUI;

import javax.swing.*;
import java.awt.*;
import view.auditlog;
import view.kasir;
import view.laporanKeuangan;
import view.stok;

public class home extends javax.swing.JFrame {
    

    private CardLayout cardLayout;
    
    public home() {
        initComponents();
        resizeLogo();
        // Tambahkan ini setelah initComponents()
        setBackground(new java.awt.Color(0, 0, 0, 0)); // Alpha = 0 untuk transparan total
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        uASPBO1 = new view.UASPBO();
        btnStock3 = new javax.swing.JButton();
        btnAudit3 = new javax.swing.JButton();
        btnKasir3 = new javax.swing.JButton();
        btnLaporan3 = new javax.swing.JButton();
        btnLogout3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        uASPBO2 = new view.UASPBO();
        contentPanel = new javax.swing.JPanel();
        uASPBO4 = new view.UASPBO();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kasir- Bening Work");
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setToolTipText("");
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(1080, 720));

        uASPBO1.setBackground(new java.awt.Color(159, 2, 22));
        uASPBO1.setPreferredSize(new java.awt.Dimension(300, 531));
        uASPBO1.setRoundBottomLeft(100);
        uASPBO1.setRoundBottomRight(100);
        uASPBO1.setRoundTopLeft(100);
        uASPBO1.setRoundTopRight(100);

        btnStock3.setBackground(new java.awt.Color(13, 163, 92));
        btnStock3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnStock3.setForeground(new java.awt.Color(255, 255, 255));
        btnStock3.setText("STOCK");
        btnStock3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStock3.setPreferredSize(new java.awt.Dimension(150, 40));
        btnStock3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStock3ActionPerformed(evt);
            }
        });

        btnAudit3.setBackground(new java.awt.Color(13, 163, 92));
        btnAudit3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnAudit3.setForeground(new java.awt.Color(255, 255, 255));
        btnAudit3.setText("AUDIT");
        btnAudit3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAudit3.setPreferredSize(new java.awt.Dimension(150, 40));
        btnAudit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAudit3ActionPerformed(evt);
            }
        });

        btnKasir3.setBackground(new java.awt.Color(13, 163, 92));
        btnKasir3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnKasir3.setForeground(new java.awt.Color(255, 255, 255));
        btnKasir3.setText("KASIR");
        btnKasir3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.black, java.awt.Color.white));
        btnKasir3.setBorderPainted(false);
        btnKasir3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnKasir3.setPreferredSize(new java.awt.Dimension(150, 40));
        btnKasir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKasir3ActionPerformed(evt);
            }
        });

        btnLaporan3.setBackground(new java.awt.Color(13, 163, 92));
        btnLaporan3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        btnLaporan3.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan3.setText("LAPORAN");
        btnLaporan3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLaporan3.setPreferredSize(new java.awt.Dimension(150, 40));
        btnLaporan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporan3ActionPerformed(evt);
            }
        });

        btnLogout3.setBackground(new java.awt.Color(13, 163, 92));
        btnLogout3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnLogout3.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout3.setText("Log Out");
        btnLogout3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogout3.setPreferredSize(new java.awt.Dimension(100, 30));
        btnLogout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 219, 195));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MENU");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout uASPBO1Layout = new javax.swing.GroupLayout(uASPBO1);
        uASPBO1.setLayout(uASPBO1Layout);
        uASPBO1Layout.setHorizontalGroup(
            uASPBO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uASPBO1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(uASPBO1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(uASPBO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKasir3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(uASPBO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLaporan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStock3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAudit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uASPBO1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        uASPBO1Layout.setVerticalGroup(
            uASPBO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uASPBO1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnKasir3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnAudit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnStock3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnLaporan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnLogout3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        uASPBO2.setBackground(new java.awt.Color(255, 235, 202));
        uASPBO2.setRoundBottomLeft(100);
        uASPBO2.setRoundBottomRight(100);

        contentPanel.setBackground(new java.awt.Color(255, 235, 202));
        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout uASPBO2Layout = new javax.swing.GroupLayout(uASPBO2);
        uASPBO2.setLayout(uASPBO2Layout);
        uASPBO2Layout.setHorizontalGroup(
            uASPBO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uASPBO2Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        uASPBO2Layout.setVerticalGroup(
            uASPBO2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uASPBO2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        uASPBO4.setBackground(new java.awt.Color(216, 46, 48));
        uASPBO4.setRoundTopRight(100);

        javax.swing.GroupLayout uASPBO4Layout = new javax.swing.GroupLayout(uASPBO4);
        uASPBO4.setLayout(uASPBO4Layout);
        uASPBO4Layout.setHorizontalGroup(
            uASPBO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );
        uASPBO4Layout.setVerticalGroup(
            uASPBO4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(uASPBO1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 272, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(uASPBO2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 173, Short.MAX_VALUE)
                    .addComponent(uASPBO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(uASPBO1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(0, 223, Short.MAX_VALUE)
                    .addComponent(uASPBO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(uASPBO4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(497, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStock3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStock3ActionPerformed
        new stok().setVisible(true);
    }//GEN-LAST:event_btnStock3ActionPerformed

    private void btnLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout3ActionPerformed

    private void btnAudit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAudit3ActionPerformed
        new auditlog().setVisible(true);
    }//GEN-LAST:event_btnAudit3ActionPerformed

    private void btnLaporan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporan3ActionPerformed
        new laporanKeuangan().setVisible(true);
    }//GEN-LAST:event_btnLaporan3ActionPerformed

    private void btnKasir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKasir3ActionPerformed
        new kasir().setVisible(true);

    }//GEN-LAST:event_btnKasir3ActionPerformed

    private void resizeLogo() {
    ImageIcon icon = new ImageIcon(getClass().getResource("/asset/logo.png"));
    Image image = icon.getImage().getScaledInstance(300, 180, Image.SCALE_SMOOTH);
    jLabel2.setIcon(new ImageIcon(image));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        SwingUtilities.invokeLater(() -> new home().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAudit3;
    private javax.swing.JButton btnKasir3;
    private javax.swing.JButton btnLaporan3;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnStock3;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private view.UASPBO uASPBO1;
    private view.UASPBO uASPBO2;
    private view.UASPBO uASPBO4;
    // End of variables declaration//GEN-END:variables

}
