package view;

/**
 *
 * @author aurel
 */

import controller.DetailPenjualanController;
import controller.PemasukanController;
import controller.PengeluaranController;
import controller.AuditLogController;
import controller.BarangController;
import model.DetailPenjualan;
import model.Pemasukan;
import model.Pengeluaran;
import model.DiagramLaporan;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.awt.Image;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

public class laporanPenjualan extends javax.swing.JFrame {
    DetailPenjualanController detailPenjualanController = new DetailPenjualanController();
    PengeluaranController pengeluaranController = new PengeluaranController();
    PemasukanController pemasukanController = new PemasukanController();

    /**
     * Creates new form laporanPenjualan
     */

public laporanPenjualan() {
        initComponents();
        resizeLogo();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(237, 219, 195));

        jPanel3.setBackground(new java.awt.Color(212, 184, 147));

        jButton2.setBackground(new java.awt.Color(111, 77, 56));
        jButton2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(212, 184, 147));
        jButton2.setText("LAPORAN PENJUALAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(111, 77, 55));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(212, 184, 147));
        jButton3.setText("LAPORAN PEMBELIAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(111, 77, 56));
        jButton4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(212, 184, 147));
        jButton4.setText("CETAK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(34, 34, 34)
                .addComponent(jButton4)
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(213, 184, 147));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("LAPORAN PENJUALAN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Barang", "Jumlah", "Harga Satuan", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(159, 2, 22));
        jPanel1.setPreferredSize(new java.awt.Dimension(787, 100));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 219, 195));
        jLabel3.setText("BENING WORK");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logo5.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(304, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel6.setBackground(new java.awt.Color(213, 184, 147));

        jLabel2.setText("Total Pemasukan : Rp 0");

        jLabel4.setText("Total Pengeluaran : Rp 0");

        jLabel5.setText("Laba / Rugi : Rp 0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void resizeLogo() {
    ImageIcon icon = new ImageIcon(getClass().getResource("/asset/logo5.png"));
    Image image = icon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
    jLabel6.setIcon(new ImageIcon(image));
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String[] kolom = {"Barang", "Jumlah", "Harga Satuan", "Subtotal"};
        
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        jTable1.setModel(model);
        
        List<DetailPenjualan> daftar = detailPenjualanController.getDetailPenjualanHariIni();
        for (DetailPenjualan dp : daftar) {
            double subtotal = dp.getHargaSatuan() * dp.getJumlah();
            Object[] row = {
                dp.getNamaBarang(),
                dp.getJumlah(),
                dp.getHargaSatuan(),
                subtotal
            };
            model.addRow(row);
        }

        updateRingkasan();
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String[] kolom = {"Nama Barang", "Jumlah", "Total"};
        
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        jTable1.setModel(model);

        List<Pengeluaran> daftar = pengeluaranController.getPengeluaranHariIni();
        BarangController barangController = new BarangController();

        for (Pengeluaran p : daftar) {
            String namaBarang = barangController.getNamaBarangById(p.getBarangId());
            Object[] row = {
                namaBarang,
                p.getJumlah(),
                p.getTotal()
            };
            model.addRow(row);
        }

        updateRingkasan();
    }                                        
    
    private void updateRingkasan() {
        double totalPemasukan = pemasukanController.getAllPemasukan().stream()
                .mapToDouble(Pemasukan::getTotal).sum();

        double totalPengeluaran = pengeluaranController.getAllPengeluaran().stream()
                .mapToDouble(Pengeluaran::getTotal).sum();

        double laba = totalPemasukan - totalPengeluaran;
        
        jLabel2.setText("Total Pemasukan: Rp " + totalPemasukan);
        jLabel4.setText("Total Pengeluaran: Rp " + totalPengeluaran);
        jLabel5.setText("Laba / Rugi: Rp " + laba);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Document document = new Document();
        try {
            String tanggal = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            String folderPath = "pdf/laporan_keuangan/";
            new File(folderPath).mkdirs();
            String filePath = folderPath + "laporan_keuangan_" + tanggal + ".pdf";

            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();

            document.add(new Paragraph("Laporan Keuangan - Bening Work", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16)));
            document.add(new Paragraph("Tanggal: " + tanggal));
            document.add(Chunk.NEWLINE);

            // Tabel Pemasukan(Penjualan)
            document.add(new Paragraph("Detail Penjualan Hari Ini:"));
            PdfPTable penjualanTable = new PdfPTable(4);
            penjualanTable.setWidthPercentage(100);
            penjualanTable.addCell("Barang");
            penjualanTable.addCell("Jumlah");
            penjualanTable.addCell("Harga Satuan");
            penjualanTable.addCell("Subtotal");

            List<DetailPenjualan> daftarpenjualan = detailPenjualanController.getDetailPenjualanHariIni();
            for (DetailPenjualan dp : daftarpenjualan) {
                penjualanTable.addCell(dp.getNamaBarang());
                penjualanTable.addCell(String.valueOf(dp.getJumlah()));
                penjualanTable.addCell(String.valueOf(dp.getHargaSatuan()));
                penjualanTable.addCell(String.valueOf(dp.getJumlah() * dp.getHargaSatuan()));
            }

            document.add(penjualanTable);
            document.add(Chunk.NEWLINE);

            //Tabel Pengeluaran
            document.add(new Paragraph("Detail Pengeluaran Hari Ini:"));
            PdfPTable pengeluaranTable = new PdfPTable(3);
            pengeluaranTable.setWidthPercentage(100);
            pengeluaranTable.addCell("Barang");
            pengeluaranTable.addCell("Jumlah");
            pengeluaranTable.addCell("Subtotal");

            BarangController barangController = new BarangController();
            List<Pengeluaran> daftarPengeluaran = pengeluaranController.getPengeluaranHariIni();

            for (Pengeluaran p : daftarPengeluaran) {
                String namaBarang = barangController.getNamaBarangById(p.getBarangId());

                pengeluaranTable.addCell(namaBarang);
                pengeluaranTable.addCell(String.valueOf(p.getJumlah()));
                pengeluaranTable.addCell(String.valueOf(p.getTotal()));
            }

            document.add(pengeluaranTable);
            document.add(Chunk.NEWLINE);
            // PERHITUNGAN LABA HARI INI
            double totalPemasukanHariIni = pemasukanController.getPemasukanHariIni().stream()
                    .mapToDouble(Pemasukan::getTotal).sum();
            double totalPengeluaranHariIni = pengeluaranController.getPengeluaranHariIni().stream()
                    .mapToDouble(Pengeluaran::getTotal).sum();
            double laba = totalPemasukanHariIni - totalPengeluaranHariIni;
            double persentaseLaba = totalPemasukanHariIni != 0 ? (laba / totalPemasukanHariIni) * 100 : 0;

            PdfPTable summaryTable = new PdfPTable(2);
            summaryTable.setWidthPercentage(60);
            summaryTable.addCell("Total Pemasukan Hari Ini ");
            summaryTable.addCell("Rp " + totalPemasukanHariIni);
            summaryTable.addCell("Total Pengeluaran Hari Ini");
            summaryTable.addCell("Rp " + totalPengeluaranHariIni);
            summaryTable.addCell("Laba / Rugi");
            summaryTable.addCell("Rp " + laba);
            summaryTable.addCell("Persentase Laba");
            summaryTable.addCell(String.format("%.2f%%", persentaseLaba));

            document.add(summaryTable);

            // Tambahkan Diagram Batang
            try {
                DiagramLaporan diagram = new DiagramLaporan();
                List<DetailPenjualan> penjualanHariIni = detailPenjualanController.getDetailPenjualanHariIni();
                diagram.getDiagramPDF(document, penjualanHariIni, totalPemasukanHariIni, totalPengeluaranHariIni);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal menambahkan diagram ke PDF: " + ex.getMessage());
            }

            document.close();
            new AuditLogController().catatLog("Laporan Keuangan dicetak");

            JOptionPane.showMessageDialog(this, "Laporan berhasil disimpan ke:\n" + filePath);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal ekspor PDF: " + e.getMessage());
        }
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    
    }                                        

    /**
     * @param args the command line arguments
     */
    
public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new laporanPenjualan().setVisible(true));
    }



    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
